export enum Methods {
    ChangeQuery = "ChangeQuery",
    RestartApp = "RestartApp",
    ShellRun = "ShellRun",
    CopyToClipboard = "CopyToClipboard",
    SaveAppAllSettings = "SaveAppAllSettings",
    SavePluginSettings = "SavePluginSettings",
    ReloadAllPluginDataAsync = "ReloadAllPluginDataAsync",
    CheckForNewUpdate = "CheckForNewUpdate",
    ShowMsgError = "ShowMsgError",
    ShowMainWindow = "ShowMainWindow",
    HideMainWindow = "HideMainWindow",
    ShowMsg = "ShowMsg",
    OpenSettingDialog = "OpenSettingDialog",
    GetTranslation = "GetTranslation",
    GetAllPlugins = "GetAllPlugins",
    FuzzySearch = "FuzzySearch",
    OpenDirectory = "OpenDirectory",
    OpenUrl = "OpenUrl",
    OpenAppUri = "OpenAppUri",
    ToggleGameMode = "ToggleGameMode",
    SetGameMode = "SetGameMode",
    ReQuery = "ReQuery",
}
